### ISSUE TITLE
TypeError: key.charAt is not a function when try to get(key)

### ISSUE THREAD

**Issue by sb30** [xavi-/node-properties-parser#17]
Here is my code: 
```js
var pParser = require ("properties-parser");
var properties = pParser.read("sample-config.properties");
console.log(properties); // this has no problem, displays properties just fine

var pEditor = pParser.createEditor("sample-config.properties");
console.log(pEditor.get("userid")); // this is where the problem is, tried passing the key using both double quotes and a single quote
pEditor.set("location",["Chicago"]); // this has the same problem
pEditor.save();
```

File Contents:
```properties
username="xyz"
userid="99"
```

Node Version: v8.9.2

**Comment by xavi-** [comment]
I just tried this locally can it seemed to work property on my end.

This `console.log(pEditor.get("userid"))` returns `"99"` as you'd expect

The next line of code (`pEditor.set("location",["Chicago"])`) does throw an error, but that's because the second parameter to `set` should be string, not an array.

Let me know if you're still seeing an error.
